# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nest server CI/CD

on:
  push:
    branches: [ deploy-nest-server ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run install & test
      run: |
        npm install
        npm run test
  deploy:
    needs: [test]
    runs-on: unbuntu-latest
    steps:
    - name: Deploy nest server
      uses: appleboy/ssh-action@master
      with:
        host: {{ secrets.SSH_HOST }}
        username: {{ secrets.SSH_USERNAME }}
        key: {{ secrets.SSH_KEY }}
        port: {{ secrets.SSH_PORT }}
        script: |
          su - deployer
          cd ~/projects/QLQT_TrumSoSanh
          git pull origin deploy-nest-server
          cd server
          ./build-server
          pm2 restart 0
